name: flippable_box
description: A double-sided Container, that can flip over, revealing content on both sides.
version: 1.0.1
homepage: https://github.com/gskinnerTeam/flutter-flippable-box

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
